### ISSUE TITLE
No such namespace 

### ISSUE THREAD

**Issue by Mhsmit** [propan/clj-recaptcha#5]
No such namespace: clj-recaptcha.client-v2, could not locate clj_recaptcha/client_v2.cljs, clj_recaptcha/client_v2.cljc, or JavaScript source providing "clj-recaptcha.client-v2" (Please check that namespaces with dashes use underscores in the ClojureScript file name) 

Does this still work ?

**Comment by propan** [comment]
I have not used the library in a while and cannot say for sure, but I doubt that re-captcha has change their API.

At the same time, based on the error message, it seems that you are trying to use the library from ClojureScript, but it works only with Clojure.
